### PR TITLE
added style to artists index page + style to navbar

### PR DESCRIPTION
**Pull request by carolinavmo**

### CODE REVIEW

**Comment by carolinavmo** [comment]
Screenshot 2023-03-16 at 17-34-35 Concertify

**Comment by carolinavmo** [comment]
Screenshot 2023-03-16 at 18-05-51 Concertify

**Comment by carolinavmo** [comment]
Screenshot 2023-03-16 at 18-06-52 Concertify

**Comment by CdLeng** [comment]
nice work @carolinavmo!

**Pull request merged**
