### PR TITLE
put the map bellow the grid + changed color to lighter gray

### PR DESCRIPTION
**Pull request by carolinavmo**
Screenshot 2023-03-29 at 16-25-07 Concertify

### CODE REVIEW

**Comment by CdLeng** [comment]
@carolinavmo somehow for me the map is way below now, a lot of space between trhe concerts card and the map.
I think I like it more at the top aswell

**Comment by CdLeng** [comment]
Nice one, the map in your screenshot looks way different from mine. In my version it's still the same as before.
It seems in your screenshot the space seems more bright and the globe has a glow around it?

**Comment by carolinavmo** [comment]
Thats weird.. On mine looks like this @CdLeng 

I changed the style of the map on the javascript file

Screenshot 2023-03-30 at 16-40-25 Concertify

**Comment by CdLeng** [comment]
Very weird indeed, let's merge it anyway

**Pull request merged**
