### PR TITLE
An idea for a different version of concerts index page

### PR DESCRIPTION
**Pull request by carolinavmo**
I had an idea for a different version of concerts index page:
- Where we could use the image of the concert for the background of the cards
- On hover: it will show up the date, and if we click on it, it will redirect to the concert page

Its just on option, if you guys like it...

Screenshot 2023-03-23 at 19-38-40 Concertify

### CODE REVIEW

**Comment by isaquito1993** [comment]
the image that is in the screenshot? or what image? I worry that depending on the image, the text might not be very readable.

For example NEW ORDER in the top row is a struggle

I love the idea though

**Comment by isaquito1993** [comment]
the go back button would also need some editing

**Comment by carolinavmo** [comment]
Yeah Isaac! I also tought the same
I could add more or less opacity to make sure that the text is allways readable :) 

When we fetch the concerts, I think there will be an image for each concert from the API, and we could use that.

If not, we could have some images from the background of concerts pre-selected (from unsplash or so) and usem them just for this page.

**Comment by isaquito1993** [comment]
hmmm ok. in that case maybe we should wait and see what the images look like from the API? What do you think?

I quite like the layout. makes it more fun / dynamic

**Comment by carolinavmo** [comment]
Yes, I agree :) 
In the worst case scenario, we could do something like this, with a background white to make sure we can read

Screenshot 2023-03-23 at 20-08-50 Concertify

**Comment by isaquito1993** [comment]
nice change on the button

the background white is a no go from me. sorry 😅

**Comment by carolinavmo** [comment]
Hahaha  Noted! 👍

**Comment by CdLeng** [comment]
@carolinavmo I like it too, but I think showing the date is a must, definitely when there are multiple concerts from the same artist in the view. And maybe use white text shadow for the text so that it pops out more?

**Comment by carolinavmo** [comment]
Yeah, I understand your concern 
My tought was on hover show the date in big letter, in order to add more interactivity with the user.
But if you guys think that wouldnt work, i will add the date 

About the location, I dont think is that necessary, because we want the user to click in the cards and go to the concert page. If we show all the information on the concerts index, then the user woudnt need to go to the concert show page... 
Its just my opinion
But if you guys agree that we should put the location on there, sure I will add that as well :) 

The text-shadow doesnt work very well, so I added a background gradient radial, from white to transparent
Screenshot 2023-03-25 at 09-01-30 Concertify

**Comment by CdLeng** [comment]
@carolinavmo you're right, that would make going to the concert show less obvious.
I like it more with the date in it. Now you can remove the hover effect I think?

Also the artist search bar can dissapear in my opinion, it has no function. 

When there are no concerts maybe show some text "No concerts could be found"?
Maybe a call to action to follow more artists?

**Comment by carolinavmo** [comment]
I will do that :) 

But I have a question, what concerts will this index page show?
Because in order to have "no concerts could be found", first the user need to search for something

Can we make a search for some concert based on location and display them in the cards?
Like, search concerts in Berlin
I could add the map here, and it would show the markers

**Comment by carolinavmo** [comment]
I was doing something like this.

But I dont know if we are gonna have the map just in the concerts#show page , or also in the  concerts index#page

Screenshot 2023-03-25 at 12-21-51 Concertify

**Comment by CdLeng** [comment]
@carolinavmo  Great!

My idea was to show all the concerts from the followed artists here.
Because that would give you a nice overview. 
The map is also a really good idea, but maybe put that in a separate view?

**Comment by CdLeng** [comment]
Maybe we can discuss this later thgis afternoon, gonna get lunch now 👍

**Comment by carolinavmo** [comment]
Oh okay, it makes sence!
it would work like a recommendations page for concerts of the favourite artists

Yeah we can discuss it later

Have a nice lunch ;)

**Comment by carolinavmo** [comment]
Screenshot 2023-03-25 at 14-21-59 Concertify

**Pull request merged**
