### PR TITLE
added grid for artists index + hover effect

### PR DESCRIPTION
**Pull request by carolinavmo**

### CODE REVIEW

**Comment by carolinavmo** [comment]
Screenshot 2023-03-21 at 18-51-38 Concertify

**Comment by isaquito1993** [comment]
if possible, make it so we only see the first 4 or 6 artsits? and then a show more button that bring up another 4 or 6?

**Comment by CdLeng** [comment]
@carolinavmo @isaquito1993 I can specify the amount of results that Spotify can return. Maybe reduce it from 35 to 20 or something? Maybe even less

**Comment by CdLeng** [comment]
@carolinavmo looking nice, when a artist name exceeds the box it's currently not possible to wrap it in the next line. Because it's actually a submit button and not text. So it's more a backend thing.

A possibility would be to hide the part that goes outside the linmit of the box by doing `overflow: hidden`

**Pull request merged**
