### PR TITLE
Change welcome message to name

### PR DESCRIPTION
**Pull request by isaquito1993**
also made it so that the welcome message is to the first name and moved down the checkout these concerts message

### CODE REVIEW

**Comment by CdLeng** [comment]
@isaquito1993 nice one, although I would make the "Checkout these concerts!" text color white
Also not really sure about the placement, because a regular user is never going to see it in that place

**Comment by isaquito1993** [comment]
fair, have changed it back to white. i think the placement is ok, otherwise it feels a bit wide?

Screenshot 2023-03-19 at 17 38 27
es.githubusercontent.com/65176136/226191108-ed7b943f-40c0-4088-b27b-280f6653134d.png">

**Comment by isaquito1993** [comment]
Screenshot 2023-03-19 at 17 38 27

**Comment by isaquito1993** [comment]
Screenshot 2023-03-19 at 17 40 03

**Pull request merged**
